# Generated by Django 4.2.1 on 2023-06-01 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodgram", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
    ]
