# Generated by Django 4.2.1 on 2023-06-01 07:38

from django.db import migrations, models
import foodgram.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("foodgram", "0003_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Цвет в HEX. Пример: #000000",
                max_length=7,
                validators=[foodgram.models.validators.hex_validator],
                verbose_name="Цвет",
            ),
        ),
    ]
