# Generated by Django 4.2.1 on 2023-06-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodgram", "0004_alter_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="foodgram.tag"),
        ),
    ]
