# Generated by Django 4.2.1 on 2023-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodgram", "0007_ingredientrecipe_recipe_ingredients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="unit",
            new_name="measurement_unit",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients",
                through="foodgram.IngredientRecipe",
                to="foodgram.ingredient",
            ),
        ),
    ]
