# Generated by Django 4.2.1 on 2023-06-12 17:42

from django.db import migrations, models
import foodgram.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0015_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[foodgram.models.validators.ingredient_validator], verbose_name='Количество'),
        ),
    ]
