  name: FoodGram workflow

  on: [push]

  jobs:
    copy_project_on_server:
      name: Copy docs and infra folders
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: create app folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: rm -rf foodgram && mkdir -p foodgram && mkdir -p foodgram/docs && mkdir -p foodgram/data
          debug: true

      - name: Copy infra files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: infra
          remote: /home/${{ secrets.USER }}/foodgram/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privatekey: ${{ secrets.SSH_KEY }}

      - name: Copy docs files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: docs
          remote: /home/${{ secrets.USERNAME }}/foodgram/docs/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privatekey: ${{secrets.SSH_KEY }}

      - name: Copy data files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: data
          remote: /home/${{ secrets.USERNAME }}/foodgram/data/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privatekey: ${{secrets.SSH_KEY }}

    tests:
      name: Make tests
      runs-on: ubuntu-latest
      needs: copy_project_on_server
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r ./backend/requirements.txt 

      - name: tests
        run: |
          python -m flake8
          python ./backend/foodram_backend/manage.py test
          python -m pytest

    build_and_push_frontend_to_DockerHub:
      name: Building front image and pushing it to DockerHub
      runs-on: ubuntu-latest
      needs: tests
      steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push foodgram-frontend to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: frontend/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/foodgram_frontend:latest

    build_and_push_backend_to_DockerHub:
        name: Push backend image and pushing it to DockerHub
        runs-on: ubuntu-latest
        needs: tests
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          - name: Login to Docker
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Push to Docker Hub
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
              context: backend/
    deploy:
      runs-on: ubuntu-latest
      needs:
        - copy_project_on_server
        - build_and_push_frontend_to_DockerHub
        - build_and_push_backend_to_DockerHub
      steps:
        - name: executing remote ssh commands to deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd foodgram
              touch .env
              echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
              echo DB_NAME=${{ secrets.DB_NAME }} >> .env
              echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
              echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
              echo DB_HOST=${{ secrets.DB_HOST }} >> .env
              echo DB_PORT=${{ secrets.DB_PORT }} >> .env
              
              sudo docker-compose down
              sudo docker-compose up -d

    send_message:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!